---

version: '3'
services:
  pit-organ:
    image: hayatochiri/golang-devenv:1.13.1-alpine3.10
    container_name: pit-organ
    volumes:
      - .:/go/src/github.com/hayatochiri/pit-organ
    ports:
      - '8080:8080'
    working_dir: /go/src/github.com/hayatochiri/pit-organ
